variables:
  - &vlang_image 'git.rustybever.be/chewing_bever/vlang:0.3.3-alpine3.17'

branches:
  exclude: [ main ]

platform: 'linux/amd64'

pipeline:
  build:
    image: *vlang_image
    commands:
      - make
    when:
      event: [ push ]

  lint:
    image: *vlang_image
    commands:
      - make lint
    when:
      event: [ push ]
